# DATA ANALYSIS LIBRARY

# NumPy Basics
Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Numpy is a Data Analysis Library


###### asking for help
np.info (np.ndarray.dtype)

In [4]:
#NumPy is a Python package which stands for ‘Numerical Python’.
#It is the core library for scientific computing, which contains a powerful n-dimensional array object.

In [5]:
#Array is divided into 2 types- VECTORS AND MATRICES

In [6]:
#VECTORS

In [3]:
import numpy as np

In [4]:
#Creating 1-D array which we than call a Vector

OneD_row= np.array([1,2,3]) # if we add multiple values in a single list a row is being created.

OneD_column= np.array([[4],[5],[6]]) #if we add multiple list into the list a column is being created.

In [5]:
print(OneD_row)

print(OneD_column)

[1 2 3]
[[4]
 [5]
 [6]]


In [6]:
#Inspecting your array

OneD_row.ndim  #checks overall dimension- you can check it by square brackets 

1

In [7]:
type(OneD_row) #checks overall type of variable assigned

numpy.ndarray

In [28]:
len(OneD_row) #length of array

3

In [8]:
OneD_row.dtype #checks datatype inside an array(here, in this case vector)

dtype('int32')

In [9]:
OneD_row.size #checks number of elements inside a vector

3

In [10]:
OneD_row.reshape(1,-1)

array([[1, 2, 3]])

In [11]:
#MATRICES- can be 2-D or any D array
#Note- 2-D arrays are always dependent upon 1-D array

In [12]:
matrix= np.array([[1,2,3,4,4,5,6,7,5,6,7,8]])
matrix

array([[1, 2, 3, 4, 4, 5, 6, 7, 5, 6, 7, 8]])

In [13]:
#Inspecting your array

matrix.ndim #by seeing 2 square brackets, we can say that it is matrix and is 2-D array

2

In [14]:
type(matrix)

numpy.ndarray

In [15]:
matrix.dtype

dtype('int32')

In [16]:
matrix.size

12

In [17]:
a= matrix.reshape(4,3) 

In [18]:
a.shape

(4, 3)

In [19]:
#to convert the elements in matrix in float, use astype()

result= matrix.astype(float)
b= result.reshape(4,3)

In [20]:
b.shape

(4, 3)

In [21]:
#Creating a Matrix(2D array) of [4,3].(Note the syntax) 
#here, if we want to create a [4,3] matrix rather than reshaping so we can manually create it

arr = np.array([ [1,2,3],[4,5,6],[7,8,9],[1,3,5]])

print('2D array\n\n',arr)

2D array

 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 5]]


In [22]:
arr.ndim

2

In [23]:
arr[0][1]

2

In [24]:
#Selecting elements from a particular row or column

arr[3,1:]

array([3, 5])

In [25]:
print(arr[:,0]) #it will print whole Zeroth column

[1 4 7 1]


In [43]:
#Creating a Matrix(3D array) of [4,3]. (Note the Syntax)
#3D--> block gets starts. In 2D, the block will not be there as it is 2-D.

arr3= np.array([ [[1,2,3]],[[4,8,9]],[[5,6,7]],[[8,9,10]] ]) #check the square brackets
print('3D array \n',arr3)

3D array 
 [[[ 1  2  3]]

 [[ 4  8  9]]

 [[ 5  6  7]]

 [[ 8  9 10]]]


In [65]:
#NOTE
arr3[1,0,2] #block, row--> individual counting , column

9

In [44]:
arr3.ndim

3

In [45]:
arr3.shape #blocks,rows,columns

(4, 1, 3)

In [51]:
#Selecting elements from a particular row or column


#print(arr3[:2,2])   #it will print in mxn form

#doubt cleared. Always remember block size in 3-D matrices.

In [53]:
arr4= np.array([[ [1,2,3],[4,8,9],[5,6,7],[1,5,8] ]])
arr4

array([[[1, 2, 3],
        [4, 8, 9],
        [5, 6, 7],
        [1, 5, 8]]])

In [61]:
#NOTE
arr4[0,1,2] #block, row, column

9

In [59]:
#Printing array dimensions(axes) by default axes=0 row and axis=1 is column

arr4.ndim

3

In [66]:
#NOTE
arr4.shape

(1, 4, 3)

In [65]:
arr.dtype

dtype('int32')

In [66]:
arr.size

12

In [61]:
arr.shape

(4, 3)

# Array Creating Techniques

In [69]:
 #creating vector through list
    
list1= [1,2,3,4] 

In [70]:
a1= np.array(list1)
a1

array([1, 2, 3, 4])

In [71]:
#creating matrices through list

my_mat= [[1,2,3], [4,5,6]] 
a2= np.array(my_mat)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
#creating vector through tuple

tup= (1,2,3,4)   
a12= np.array(tup)
a12

array([1, 2, 3, 4])

In [75]:
#creating matrices through tuple

my_mat2= ((1,2,3),(4,5,6))  
a22= np.array(my_mat2)
a22

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
#Creating arrays with all zero elements and one elements

c= np.zeros((3,3))
d= np.ones((3,3))

print('Array with all zero elements:\n',c,'\n')
print('Array with all ones elements:\n',d)

Array with all zero elements:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Array with all ones elements:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [80]:
#Creating constatnt value arrays with type complex

e= np.full((2,2),6,dtype=complex)   #np.full-create array with constant elements here constant is 6
print('Complex array with constant value:,\n',e)

Complex array with constant value:,
 [[6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j]]


In [27]:
#It willl print the identity matrix.

z= np.eye(4) 
print(z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [82]:
#Creating array with random values

f= np.random.random((3,3))  
print('Create random values array:\n',f)

Create random values array:
 [[0.90160627 0.24125674 0.11252127]
 [0.30990454 0.62636109 0.86349873]
 [0.40299349 0.8786817  0.82007529]]


In [87]:
o= np.random.rand(5,5)
o

array([[0.51327752, 0.79466953, 0.45242957, 0.27286623, 0.2333167 ],
       [0.54176719, 0.77359727, 0.63433345, 0.90221899, 0.38103672],
       [0.84279112, 0.04973945, 0.2818334 , 0.98390846, 0.84479618],
       [0.07735886, 0.30658231, 0.65617781, 0.42255498, 0.55808347],
       [0.92350543, 0.44946426, 0.05268274, 0.67317406, 0.26470438]])

In [89]:
#returns evenly spaced numbers over specified interval

q= np.linspace(0,5,10) 
q

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [83]:
#Creating a sequencing of integers from 0 to 30 with steps of 5

g= np.arange(0,31,5)        #it will print an sequence of numbers from 0 to 30 with difference of 5
print('Sequencing:\n',g)    #and then can reshape of your own choice

Sequencing:
 [ 0  5 10 15 20 25 30]


In [98]:
v= np.full((2,2), 99)
v

array([[99, 99],
       [99, 99]])

In [108]:
#Reshaping the 3X4 array into 2X6 array

h= np.array([[1,2,3,0],[4,5,6,8],[7,8,9,5]])
print('Original array:\n',h)

print("\n")

newarray= h.reshape(2,6)      #converting a 3X4 array into 2X6 array (note-while reshaping size of the arrays(No.of elements) should not be changed)
print('Reshaped array:\n',newarray)

print("\n")

array= h.reshape(2,2,3)      #Converting array of 3X4 into two different 3X2 array 
print('Reshaped array:\n',array)


Original array:
 [[1 2 3 0]
 [4 5 6 8]
 [7 8 9 5]]


Reshaped array:
 [[1 2 3 0 4 5]
 [6 8 7 8 9 5]]


Reshaped array:
 [[[1 2 3]
  [0 4 5]]

 [[6 8 7]
  [8 9 5]]]


In [99]:
# Vertically stacking vectors--> means rows

v1 = np.array([[1],[2],[3],[4]])
v2 = np.array([[5],[6],[7],[8]])

v3 =np.vstack([v1,v2])
print(v3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [100]:
v3.ndim

2

In [101]:
v1.ndim

2

In [102]:
# Horizontal  stack--> means column

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h3 = np.hstack((h1,h2)) #or can use above example and convert into hstack
print(h3)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [107]:
#converting a 2D array into 1D array using flatten
#flatten- changes dimension into 1D always

i= np.array([[1,2,3],[4,5,6]])
print('Original 2D array:\n',i)

print("\n")

j= i.flatten()
print('Flatten array:\n',j)

Original 2D array:
 [[1 2 3]
 [4 5 6]]


Flatten array:
 [1 2 3 4 5 6]


# Slicing an Array

In [111]:
#Creating array by selecting any row and column you want

array= np.array([[1,2,3,4],[5,-0.9,6,9],[9,5,7,8],[-9,7,9,2]])

s= array[1:4]      # it will print from first row till (4-1)th row
t= array[:2]       # it will print from 0th row to (2-1)th row
u= array[:,0:1]    #it will print all rows and 0th column
w= array[1:4,0:2]

print('Orignal array:\n',array,'\n')

print('Print s:\n',s,'\n')
print('Print t:\n',t,'\n')
print('Print u:\n',u ,'\n')
print(w)

Orignal array:
 [[ 1.   2.   3.   4. ]
 [ 5.  -0.9  6.   9. ]
 [ 9.   5.   7.   8. ]
 [-9.   7.   9.   2. ]] 

Print s:
 [[ 5.  -0.9  6.   9. ]
 [ 9.   5.   7.   8. ]
 [-9.   7.   9.   2. ]] 

Print t:
 [[ 1.   2.   3.   4. ]
 [ 5.  -0.9  6.   9. ]] 

Print u:
 [[ 1.]
 [ 5.]
 [ 9.]
 [-9.]] 

[[ 5.  -0.9]
 [ 9.   5. ]
 [-9.   7. ]]


In [112]:
array= np.array([[1,2,3,4],[5,-0.9,6,9],[9,5,7,8],[-9,7,9,2]])

print(array[2,1])
array[1,1]= 100  

print(array[2,1])
array
#here we had one element of the array and print the new one

5.0
5.0


array([[  1.,   2.,   3.,   4.],
       [  5., 100.,   6.,   9.],
       [  9.,   5.,   7.,   8.],
       [ -9.,   7.,   9.,   2.]])

In [113]:
#Creating array by selecting any row and column you want

arr= np.array([[1,2,3,4],[5,0.9,6,9],[9,5,7,8],[-9,7,9,2]])
select= array[:2,::2]   #:2 will select first two rows and ::2 will select alternate columns from the given array
print('Orignal array:\n',arr,'\n')
print('This are the rows and columns:\n',select)

Orignal array:
 [[ 1.   2.   3.   4. ]
 [ 5.   0.9  6.   9. ]
 [ 9.   5.   7.   8. ]
 [-9.   7.   9.   2. ]] 

This are the rows and columns:
 [[1. 3.]
 [5. 6.]]


In [114]:
arr.astype(int) 

array([[ 1,  2,  3,  4],
       [ 5,  0,  6,  9],
       [ 9,  5,  7,  8],
       [-9,  7,  9,  2]])

In [115]:
arr.astype(float)

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  0.9,  6. ,  9. ],
       [ 9. ,  5. ,  7. ,  8. ],
       [-9. ,  7. ,  9. ,  2. ]])

In [117]:
#Boolean array indexing

cond= arr > 5    #it is the synatx for printing elements of an array which is geater then 0
temp= arr[arr>5]  

print('No.is greatet than zero:\n',temp)

No.is greatet than zero:
 [6. 9. 9. 7. 8. 7. 9.]


In [118]:
cond

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True, False]])

In [119]:
print('No.is greatet than zero:\n',arr[arr>5])

No.is greatet than zero:
 [6. 9. 9. 7. 8. 7. 9.]


In [120]:
condition= arr>5

print(condition,'\n')
print(arr[condition])

[[False False False False]
 [False False  True  True]
 [ True False  True  True]
 [False  True  True False]] 

[6. 9. 9. 7. 8. 7. 9.]


# Arithmetic Operations within an Array

In [29]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

print('Printing a by adding 1 to each element:\n',a+1)

#Similarly we can do for subtraction,multiplication and Division

Printing a by adding 1 to each element:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [30]:
#double the elemnts in an array

#Note- matrix multiplication works diffrent in matrices by using dot or mul operator 

b= np.array([[1,2,3],[4,5,6],[7,8,9]])
b*= 2   #syntax for doubling the elements in array

print('Printing elements by doubling it:\n',b)

Printing elements by doubling it:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [31]:
#Transpose of an array

c=np.array([[9,7,8],[4,5,6],[1,2,3]])

print('Printing Original array:\n',c,'\n')

print('Printing transpose of an array:\n',c.T)  #Synatx for transposing an array

Printing Original array:
 [[9 7 8]
 [4 5 6]
 [1 2 3]] 

Printing transpose of an array:
 [[9 4 1]
 [7 5 2]
 [8 6 3]]


In [32]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [33]:
np.sin(a) #similarly cos ...log...also done below

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

# Urinary Operators

In [129]:
z=np.array([[1,2,3],[4,5,6],[9,8,7]])

#Aggregate functions

print('Original Array:\n',z)
print('Largest element in an array:\n',z.max())
print('Row-wise maximum element in an array:\n',z.max(axis=0))
print('Column-wise maximumm element:\n',z.max(axis=1))
print('Column-wise minimum element in array:\n',z.min(axis=1))
print('Sum of all element of an array:\n',z.sum())
print('Sum of all element of an array:\n',z.sum(axis=0))
print('Cumulative sum along column wise:\n',z.cumsum(axis=0)) #cumulative sum of elements of elements
                                                              #it will add print 1st col as it is second col by adding first and second col and third col by addin all the three col.
#Axis=0 represents Rows and Axis=1 represents Columns

Original Array:
 [[1 2 3]
 [4 5 6]
 [9 8 7]]
Largest element in an array:
 9
Row-wise maximum element in an array:
 [9 8 7]
Column-wise maximumm element:
 [3 6 9]
Column-wise minimum element in array:
 [1 4 7]
Sum of all element of an array:
 45
Sum of all element of an array:
 [14 15 16]
Cumulative sum along column wise:
 [[ 1  2  3]
 [ 5  7  9]
 [14 15 16]]


In [130]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [131]:
# Find mean of all numbers in an array
arr2.mean()

10.0

In [132]:
# Find median of all numbers present in arr2
np.median(arr2)

10.0

In [133]:
# Variance
np.var(arr2)

30.0

In [134]:
# Standard deviation
np.std(arr2)

5.477225575051661

In [135]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [136]:
# Take the cos
np.cos(a)


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

# Binary Operators

In [127]:
x=np.array([[4,6],[1,2]])
y=np.array([[3,5],[7,8]])

print('Addition of x and y:\n',x+y)
print('Subtraction of x from y:\n',x-y)
print('Multiplication of x and y:\n',x*y)   #x*y is an element multiplication
print('Matrix multiplication of x and y:\n',np.matmul(x,y) )  #x.dot(y) is and matrix mupltiplication

print(x)
print(y)

Addition of x and y:
 [[ 7 11]
 [ 8 10]]
Subtraction of x from y:
 [[ 1  1]
 [-6 -6]]
Multiplication of x and y:
 [[12 30]
 [ 7 16]]
Matrix multiplication of x and y:
 [[54 68]
 [17 21]]
[[4 6]
 [1 2]]
[[3 5]
 [7 8]]
